[project]
name = "csawesome2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "pretext>=2.19.1",
    "ruff>=0.11.10",
]
